name: Prerequisites

on:
  pull_request:
    types: [synchronize, opened, edited, ready_for_review, reopened, unlocked]
    branches: [main, development]
  push:
    branches: [main, development]

permissions:
  checks: write
  contents: write
  pull-requests: write

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install dependencies
      run: npm install

    - name: Run tests and generate coverage
      uses: ArtiomTr/jest-coverage-report-action@v2.3.0
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        threshold: 90